### successful GET req for single resource
# GET http://localhost:3001/api/persons/6127deab3c9b1c4897fa6fb2
GET https://enigmatic-journey-43702.herokuapp.com/api/persons/6127deab3c9b1c4897fa6fb2

### unsuccessful GET req for non-existing resource
# GET http://localhost:3001/api/persons/6129cf6ffe935308e4e0d9eb
GET https://enigmatic-journey-43702.herokuapp.com/api/persons/6129cf6ffe935308e4e0d9eb

### unsuccessful GET req for invalid id
# GET http://localhost:3001/api/persons/456invalidid789
GET https://enigmatic-journey-43702.herokuapp.com/api/persons/456invalidid789